# Generated by Django 5.2 on 2025-05-04 21:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_boutique_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de Boutique',
                'verbose_name_plural': 'Catégories de Boutiques',
                'db_table': 'categories_boutiques',
            },
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, upload_to='boutique_logos/', verbose_name='Logo')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('image', models.ImageField(blank=True, upload_to='boutique_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marchand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to='users.marchand', verbose_name='Marchand')),
                ('category_boutique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to='boutique.categoryboutique', verbose_name='Catégorie Boutique')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'db_table': 'boutiques',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_produit_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_produits', to='boutique.boutique', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Catégorie de Produit',
                'verbose_name_plural': 'Catégories de Produits',
                'db_table': 'categories_produits',
            },
        ),
        migrations.CreateModel(
            name='Echange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to='boutique.boutique')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Échange',
                'verbose_name_plural': 'Échanges',
                'db_table': 'echanges',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produit_images/', verbose_name='Image')),
                ('couleur', models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur')),
                ('taille', models.CharField(blank=True, max_length=50, null=True, verbose_name='Taille')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutique.boutique', verbose_name='Boutique')),
                ('category_produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutique.categoryproduit', verbose_name='Catégorie Produit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'produits',
            },
        ),
    ]
