# Generated by Django 5.2 on 2025-05-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_boutique_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boutique_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='boutique_logos/', verbose_name='Logo'),
        ),
    ]
