# Generated by Django 5.2 on 2025-05-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_alter_boutique_image_alter_boutique_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutique',
            name='status',
        ),
        migrations.AlterField(
            model_name='boutique',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='boutique_images/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=models.ImageField(blank=True, default=1, upload_to='boutique_logos/', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
