# Generated by Django 5.2 on 2025-05-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_remove_boutique_status_alter_boutique_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='en_stock',
            field=models.BooleanField(default=True, verbose_name='En stock'),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_mis_en_avant',
            field=models.BooleanField(default=False, verbose_name='Est mis en avant'),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_nouveau',
            field=models.BooleanField(default=False, verbose_name='Est nouveau'),
        ),
        migrations.AddField(
            model_name='produit',
            name='note',
            field=models.FloatField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_reduit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix réduit'),
        ),
    ]
