# Generated by Django 5.2 on 2025-05-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
