# Generated by Django 5.2 on 2025-05-15 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_remove_produit_note_produit_average_rating_rating'),
        ('users', '0006_client_orders_alter_client_historique_achats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='marchand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='users.marchand', verbose_name='Marchand'),
        ),
    ]
