# Generated by Django 5.2 on 2025-05-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_produit_marchand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='est_nouveau',
            field=models.BooleanField(default=True, verbose_name='Est nouveau'),
        ),
    ]
