# Generated by Django 5.2 on 2025-05-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemiseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, verbose_name='Désignation')),
                ('type_remise', models.CharField(choices=[('tranches', 'Remise par tranches'), ('fin_paiement', 'Remise à la fin de paiement')], max_length=20, verbose_name='Type de remise')),
                ('nombre_tranches', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de tranches déclencheur')),
                ('pourcentage_remise', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pourcentage de remise')),
                ('montant_max_remise', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant maximal de remise')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Type de remise',
                'verbose_name_plural': 'Types de remises',
                'ordering': ['-date_creation'],
            },
        ),
    ]
