# Generated by Django 5.2 on 2025-05-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
        ('config', '0002_remisetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisetype',
            name='boutique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='remise_types', to='boutique.boutique', verbose_name='Boutique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remisetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterModelTable(
            name='remisetype',
            table='remise_types',
        ),
        migrations.DeleteModel(
            name='Configurer',
        ),
    ]
