# Generated by Django 5.2 on 2025-05-06 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
        ('config', '0003_remisetype_boutique_remisetype_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remisetype',
            name='boutique',
        ),
        migrations.RemoveField(
            model_name='remisetype',
            name='updated_at',
        ),
        migrations.AlterModelTable(
            name='remisetype',
            table=None,
        ),
        migrations.CreateModel(
            name='Configurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametre', models.TextField(verbose_name='Paramètre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='boutique.boutique', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'db_table': 'configurations',
            },
        ),
    ]
