# Generated by Django 5.2 on 2025-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_remisetype_boutique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remisetype',
            name='designation',
        ),
        migrations.AddField(
            model_name='remisetype',
            name='duree_plan_paiement',
            field=models.CharField(max_length=100, null=True, verbose_name='Durée du plan de paiement'),
        ),
    ]
