# Generated by Django 5.2 on 2025-05-10 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_remove_remisetype_designation_and_more'),
        ('users', '0004_merge_20250507_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('threshold', models.IntegerField()),
                ('discount', models.FloatField()),
                ('icon', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'config_badges',
            },
        ),
        migrations.CreateModel(
            name='ReferralRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referrals_count', models.IntegerField()),
                ('discount', models.FloatField()),
                ('time_frame', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Referral Rule',
                'verbose_name_plural': 'Referral Rules',
                'db_table': 'referral_rules',
            },
        ),
        migrations.AlterModelTable(
            name='remisetype',
            table='remise_types',
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_discounts', to='users.client')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('badge', 'Badge'), ('referral', 'Referral'), ('system', 'System')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.client')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
            },
        ),
    ]
