# Generated by Django 5.2 on 2025-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_badge_referralrule_alter_remisetype_table_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
