# Generated by Django 5.2 on 2025-05-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_alter_badge_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralrule',
            old_name='referrals_count',
            new_name='referrals_Count',
        ),
        migrations.RenameField(
            model_name='referralrule',
            old_name='time_frame',
            new_name='time_Frame',
        ),
    ]
