# Generated by Django 5.2 on 2025-05-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_rename_referrals_count_referralrule_referrals_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralrule',
            old_name='referrals_Count',
            new_name='referrals_count',
        ),
        migrations.RemoveField(
            model_name='referralrule',
            name='time_Frame',
        ),
        migrations.AddField(
            model_name='referralrule',
            name='time_frame',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
