# Generated by Django 5.2 on 2025-05-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_rename_referrals_count_referralrule_referrals_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralrule',
            old_name='referrals_count',
            new_name='referralsCount',
        ),
        migrations.RenameField(
            model_name='referralrule',
            old_name='time_frame',
            new_name='timeFrame',
        ),
    ]
