# Generated by Django 5.2 on 2025-05-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
