# Generated by Django 5.2 on 2025-05-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_phone_order_telephone_remove_order_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='adresse',
        ),
    ]
