# Generated by Django 5.2 on 2025-05-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_remove_boutique_status_alter_boutique_image_and_more'),
        ('cart', '0006_remove_orderitem_order_remove_orderitem_produit_and_more'),
        ('users', '0004_merge_20250507_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='boutique.produit')),
            ],
            options={
                'verbose_name': 'Article de Commande',
                'verbose_name_plural': 'Articles de Commande',
                'db_table': 'order_items',
            },
        ),
    ]
