# Generated by Django 5.2 on 2025-05-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_orderitem'),
        ('config', '0006_remove_remisetype_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echantient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche', models.PositiveIntegerField(help_text='Numéro de la tranche de paiement, dérivé de RemiseType.nombre_tranches', verbose_name='Tranche')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant initial de la tranche, dérivé de OrderItem.prix', max_digits=10, verbose_name='Montant')),
                ('date_paiement', models.DateTimeField(help_text='Date prévue pour le paiement de la tranche, calculée automatiquement', verbose_name='Date de paiement')),
                ('date_ordre', models.DateTimeField(help_text='Date de création de la commande, dérivée de Order.created_at', verbose_name="Date de l'ordre")),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], help_text='Statut de la commande, dérivé de Order.status', max_length=20, verbose_name='Statut')),
                ('type_remise', models.CharField(choices=[('tranches', 'Remise par tranches'), ('fin_paiement', 'Remise à la fin de paiement')], help_text='Type de remise, dérivé de RemiseType.type_remise', max_length=20, verbose_name='Type de remise')),
                ('remise_appliquee', models.DecimalField(decimal_places=2, default=0.0, help_text='Montant de la remise appliquée', max_digits=10, verbose_name='Remise appliquée')),
                ('montant_apres_remise', models.DecimalField(decimal_places=2, help_text='Montant après application de la remise', max_digits=10, verbose_name='Montant après remise')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='cart.order', verbose_name='Commande')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='cart.orderitem', verbose_name='Article de commande')),
                ('remise_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_schedules', to='config.remisetype', verbose_name='Type de remise')),
            ],
            options={
                'verbose_name': 'Échéancier',
                'verbose_name_plural': 'Échéanciers',
                'db_table': 'echantients',
                'ordering': ['date_paiement'],
            },
        ),
    ]
