# Generated by Django 5.2 on 2025-05-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_echantient'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_tranches',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.DeleteModel(
            name='Echantient',
        ),
    ]
