# Generated by Django 5.2 on 2025-05-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_order_status'),
        ('users', '0005_client_current_badge_alter_client_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_Client', to='users.client'),
        ),
    ]
