# Generated by Django 5.2 on 2025-05-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_nombre_clients_parraines_client_referral_code'),
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
    ]
