# Generated by Django 5.2 on 2025-05-10 15:10

import config.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_badge_referralrule_alter_remisetype_table_discount_and_more'),
        ('users', '0004_merge_20250507_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='config.badge'),
        ),
        migrations.AlterField(
            model_name='client',
            name='referral_code',
            field=models.CharField(blank=True, default=config.models.generate_referral_code, max_length=10, null=True, unique=True),
        ),
    ]
