# Generated by Django 5.2 on 2025-05-10 17:40

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_current_badge_alter_client_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='historique_achats',
            field=models.TextField(blank=True, default='{"orders": []}', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='referral_code',
            field=models.CharField(blank=True, default=users.models.generate_referral_code, max_length=10, null=True, unique=True),
        ),
    ]
