# Generated by Django 5.2 on 2025-05-15 07:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_client_orders_alter_client_historique_achats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marchand',
            options={'verbose_name': 'Marchand', 'verbose_name_plural': 'Marchands'},
        ),
        migrations.AddField(
            model_name='marchand',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='marchand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marchand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='marchand',
            name='is_marchant',
            field=models.BooleanField(default=True, verbose_name='Est marchand'),
        ),
        migrations.AlterField(
            model_name='marchand',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='marchand_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
